#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.connection-test-query=SELECT NOW() FROM dual

# ??? ??
spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: 1234

  # ?? ?? ?? ??? ??
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

  # ???? ?? OFF
  thymeleaf:
    cache: 'false'

  # JPA ??
  jpa:
#    database: mariadb
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'